FROM node:18-bullseye-slim

WORKDIR /usr/app

COPY package.json pnpm-lock.yaml ./
COPY prisma ./prisma

RUN npm install -g pnpm && pnpm install && pnpm prisma generate

COPY . .

ARG NODE_ENV=development
ENV NODE_ENV=${NODE_ENV}

EXPOSE 3333

CMD ["pnpm","start:dev"]