name: Deploy to VPS via Rsync

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  deploy:
    name: Deploy Job
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Deploy with rsync
        uses: easingthemes/ssh-deploy@v5.0.0
        with:
          REMOTE_HOST: ${{ secrets.VPS_HOST }}
          REMOTE_USER: ${{ secrets.VPS_USER }}
          TARGET: ${{ secrets.VPS_TARGET_PATH }}

          SSH_PRIVATE_KEY: ${{ secrets.VPS_SSH_PRIVATE_KEY }}

          SOURCE: "./server"
          EXCLUDE: "/.git/, /.github/, /node_modules/, /server/.env"
          ARGS: "-avz --delete"

          SCRIPT_AFTER: |
            cd ${{ secrets.VPS_TARGET_PATH }}/server
            bash start.sh
