name: Deploy via rsync + SSH

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Sync server code to VPS via rsync
        env:
          SSH_PRIVATE_KEY: ${{ secrets.VPS_SSH_KEY }}
          VPS_USER: ${{ secrets.VPS_USER }}
          VPS_HOST: ${{ secrets.VPS_HOST }}
          VPS_APP_DIR: ${{ secrets.VPS_APP_DIR }}
        run: |
          echo "$SSH_PRIVATE_KEY" > key.pem
          chmod 600 key.pem

          rsync -avz --delete -e "ssh -i key.pem -o StrictHostKeyChecking=no" ./server/ ${VPS_USER}@${VPS_HOST}:${VPS_APP_DIR}/

      - name: Run deploy script on VPS
        uses: appleboy/ssh-action@v0.1.6
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USER }}
          key: ${{ secrets.VPS_SSH_KEY }}
          script: |
            chmod +x ${VPS_APP_DIR}/deploy.sh
            ${VPS_APP_DIR}/deploy.sh
