name: Deploy to VPS via Rsync

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  deploy:
    name: Deploy Job
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Deploy with rsync
        uses: easingthemes/ssh-deploy@v5.0.0
        with:
          REMOTE_HOST: ${{ secrets.VPS_HOST }}
          REMOTE_USER: ${{ secrets.VPS_USER }}

          SSH_PRIVATE_KEY: ${{ secrets.VPS_SSH_PRIVATE_KEY }}

          SOURCE: "./server/"

          TARGET: ${{ secrets.VPS_TARGET_PATH }}/server/

          # Não precisamos mais excluir o .env, pois ele não está sendo gerenciado aqui
          EXCLUDE: "/.git/, /.github/, /node_modules/"

          ARGS: "-avz"

          SCRIPT_AFTER: |
            cd ${{ secrets.VPS_TARGET_PATH }}/server

            echo "✅ Reiniciando a aplicação..."
            bash deploy.sh 

            echo "🎉 Deploy concluído com sucesso!"
