name: 🚀 Deploy to GH Registry and VPS

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Log in to GitHub Container Registry
        run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin

      - name: Build Docker image
        run: |
          cd server
          docker build -t ghcr.io/${{ github.repository_owner }}/kanban-app:latest .

      - name: Push Docker image
        run: docker push ghcr.io/${{ github.repository_owner }}/kanban-app:latest

      - name: Deploy to VPS
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USER }}
          key: ${{ secrets.VPS_SSH_PRIVATE_KEY }}
          script: |
            echo "🔐 Logging in to GHCR..."
            echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin

            echo "📂 Changing directory to 'server'..."
            cd server

            echo "⬇️ Pulling latest image..."
            docker compose pull

            echo "♻️ Recreating containers..."
            docker compose up -d --force-recreate
